adding timestamp for init verification endpoint and phone-hash label
codeready-toolchain/api pull request #183
Opened 2020-09-02 03:57 UTC by tinakurian

## Description
I think there may be an edge case that disallows us to re-use the `verification-timestamp` for both the init verification endpoint as well as the verify code endpoint.
 
as a user, if a user max's out generating new verification codes and the daily limit is reached i would need to wait until the `verification-timestamp` has elapsed 24hrs. then if the user then goes ahead and attempts verifying incorrect codes prior to the `verification-timestamp` elapsing 24hrs,  they will max out the attempts allowed. now, if the user waits until 24hrs has elapsed and invokes the init verification endpoint, we would reset the verification-timestamp and the counter (similar to what is done here): https://github.com/codeready-toolchain/registration-service/blob/master/pkg/verification/verification_service.go#L106-L111

however, when the user attempts to call the verify code endpoint at this point, the verification-timestamp has been reset and hence the max attempts for the verify code endpoint would not be reset.. 

this PR is to add a new timestamp label for the init verification endpoint and to also add the phone-hash label for CRT-800..

please do suggest alternative names for the labels, i don't feel too content with the name i have for the new timestamp

## Checks
1. Have you run `make generate` target? **[yes/no]**
yes
2. Does `make generate` change anything in other projects (host-operator, member-operator, toolchain-common)? **[yes/no]** 
(NOTE: You can ignore it if the only changes are in the annotation `alm-examples` of the `ClusterServiceVersion` object)
no

2020-09-02 20:20 UTC, sbryzak requested changes
Looks good, but we will need a counter also.  Maybe something like `UserSignupVerificationSentCounterAnnotationKey`

2020-09-02 20:20 UTC, sbryzak commented on pkg/apis/toolchain/v1alpha1/usersignup_types.go
> +	UserSignupVerificationCodeGeneratedTimestampAnnotationKey = LabelKeyPrefix + "verification-code-generated-timestamp"
perhaps UserSignupVerificationInitTimestampAnnotationKey

2020-09-02 20:51 UTC, tinakurian commented on pkg/apis/toolchain/v1alpha1/usersignup_types.go
> +	UserSignupVerificationCodeGeneratedTimestampAnnotationKey = LabelKeyPrefix + "verification-code-generated-timestamp"
> Looks good, but we will need a counter also. Maybe something like `UserSignupVerificationSentCounterAnnotationKey`

thanks @sbryzak we already have a counter: https://github.com/codeready-toolchain/api/blob/master/pkg/apis/toolchain/v1alpha1/usersignup_types.go#L22

2020-09-02 20:54 UTC, tinakurian commented on pkg/apis/toolchain/v1alpha1/usersignup_types.go
> +	UserSignupVerificationCodeGeneratedTimestampAnnotationKey = LabelKeyPrefix + "verification-code-generated-timestamp"
updated the name here: d3973f4f75604d4552cb391313ddc1dc89836813

2020-09-02 20:54 UTC, tinakurian commented
> Looks good, but we will need a counter also. Maybe something like `UserSignupVerificationSentCounterAnnotationKey`

thanks @sbryzak we already have a counter: https://github.com/codeready-toolchain/api/blob/master/pkg/apis/toolchain/v1alpha1/usersignup_types.go#L22

2020-09-03 02:40 UTC, sbryzak approved these changes

2020-09-03 12:07 UTC, merged