metrics: add field to store metrics in ToolchainStatus
codeready-toolchain/api pull request #224
Opened 2021-04-06 16:17 UTC by xcoulon

also, add following constants:
- `UsersPerActivationMetricKey` to store the current "Users per Activations"
  counter in the ToolchainStatus metrics
- `UserSignupActivationCounterAnnotationKey` to track the number
  of activations of a user, using an annotation on her `UserSignup` resource.

Fixes https://issues.redhat.com/browse/CRT-988

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

2021-04-06 16:25 UTC, alexeykazakov approved these changes

2021-04-06 16:25 UTC, alexeykazakov commented on pkg/apis/toolchain/v1alpha1/usersignup_types.go
> +	UserSignupUnableToRemoveFinalizerReason        = "UnableToRemoveFinalizer"
Do you need this too?

2021-04-06 16:37 UTC, alexeykazakov requested changes
I have a couple of questions to clarify...

2021-04-06 16:37 UTC, alexeykazakov commented on pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go
> +	Metrics map[string]string `json:"metrics,omitempty"`
This should be optional, right? Also, shouldn't we specify the map type / merge strategy?

2021-04-07 06:13 UTC, xcoulon commented on pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go
> +	Metrics map[string]string `json:"metrics,omitempty"`
good point. Let me add that

2021-04-08 09:28 UTC, MatousJobanek commented on pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go
> +	Metrics map[string]string `json:"metrics,omitempty" patchStrategy:"merge"`
I'm sorry for my dumb question - what is the expected content of this map?
From the code I would assume:
```
status:
  metrics:
    UsersPerActivation: '{"1":2,"2":2,"3":1,"4":1,"5":1,"6":1,"7":1,"8":1}'
```
if so,
* shouldn't be the first letter of `UsersPerActivation` lower-case - as the rest of the keys? `usersPerActivation`
* why storing the values in the json format and dealing with marshaling & unmarshaling? Is there any benefit?

2021-04-08 10:15 UTC, MatousJobanek commented on pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go
> +	Metrics map[string]string `json:"metrics,omitempty" patchStrategy:"merge"`
I mean, why not storing it as a map?

2021-04-08 11:31 UTC, xcoulon commented on pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go
> +	Metrics map[string]string `json:"metrics,omitempty" patchStrategy:"merge"`
we can't put `interface{}` values, so I opted for a string by serializing the JSON content

2021-04-08 11:32 UTC, xcoulon commented on pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go
> +	Metrics map[string]string `json:"metrics,omitempty" patchStrategy:"merge"`
> I'm sorry for my dumb question - what is the expected content of this map?
> From the code I would assume:
> 
> ```
> status:
>   metrics:
>     UsersPerActivation: '{"1":2,"2":2,"3":1,"4":1,"5":1,"6":1,"7":1,"8":1}'
> ```
> 
> if so,
> 
> * shouldn't be the first letter of `UsersPerActivation` lower-case - as the rest of the keys? `usersPerActivation`
ok, I can do that

2021-04-08 11:38 UTC, xcoulon commented on pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go
> +	Metrics map[string]string `json:"metrics,omitempty" patchStrategy:"merge"`
> > I'm sorry for my dumb question - what is the expected content of this map?
> > From the code I would assume:
> > ```
> > status:
> >   metrics:
> >     UsersPerActivation: '{"1":2,"2":2,"3":1,"4":1,"5":1,"6":1,"7":1,"8":1}'
> > ```
> > 
> > 
> > if so,
> > 
> > * shouldn't be the first letter of `UsersPerActivation` lower-case - as the rest of the keys? `usersPerActivation`
> 
> ok, I can do that

done in bf67281

2021-04-08 12:40 UTC, MatousJobanek commented on pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go
> +	Metrics map[string]string `json:"metrics,omitempty" patchStrategy:"merge"`
I meant something like:
```
map[string]map[string]int
```

2021-04-08 14:42 UTC, xcoulon commented on pkg/apis/toolchain/v1alpha1/usersignup_types.go
> +	UserSignupUnableToRemoveFinalizerReason        = "UnableToRemoveFinalizer"
removed since we decided not to decrease the counter and metrics when a user is deleted

2021-04-08 14:46 UTC, xcoulon commented on pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go
> +	Metrics map[string]string `json:"metrics,omitempty"`
done in 9f6680e

2021-04-08 14:49 UTC, xcoulon commented on pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go
> +	Metrics map[string]string `json:"metrics,omitempty" patchStrategy:"merge"`
> I meant something like:
> 
> ```
> map[string]map[string]int
> ```

the code generation fails with the following error: 
```
github.com/codeready-toolchain/api/pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go:92:21: map values must be a named type, not *ast.MapType
```

2021-04-08 14:51 UTC, xcoulon commented on pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go
> +	Metrics map[string]string `json:"metrics,omitempty" patchStrategy:"merge"`
actually, the code generation does not fail if I use something like 
```
map[string]Metric
```
with 
```
type Metric map[string]int 
```
so let me see if this solution can work up to the E2E tests

2021-04-09 08:12 UTC, xcoulon commented on pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go
> +	Metrics map[string]string `json:"metrics,omitempty" patchStrategy:"merge"`
done in 31fcd86 (and subsequently in https://github.com/codeready-toolchain/host-operator/pull/401/commits/04b0eca1e7343f4ad7fd943c747ad2e33625df7c) and it worked with the E2E tests on my temp cluster

2021-04-09 15:04 UTC, alexeykazakov approved these changes

2021-04-12 13:07 UTC, MatousJobanek approved these changes
Awesome! Thanks a lot for changing the type of the stored value :+1:

2021-04-12 13:07 UTC, MatousJobanek commented on pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go
> +	// Metrics is a map that stores (seralized) metrics to be exposed on Prometheus.
```suggestion
	// Metrics is a map that stores metrics to be exposed on Prometheus.
```

2021-04-19 08:03 UTC, xcoulon commented on pkg/apis/toolchain/v1alpha1/toolchainstatus_types.go
> +	// Metrics is a map that stores (seralized) metrics to be exposed on Prometheus.
indeed, this comment needs to be updated now ;)

2021-04-26 07:46 UTC, merged