Provisioning user signup
codeready-toolchain/api pull request #320
Opened 2022-09-02 14:58 UTC by ranakan19

## Description
adding a condition type and condition reason to indicate usersignup provisioning is in progress.

## Checks
1. Did you run `make generate` target? **yes**

2. Did `make generate` change anything in other projects (host-operator, member-operator)? **no**

3. In case of **new** CRD, did you the following? **NA**
    - make/generate.mk in this repository
    - `resources/setup/roles/host.yaml` in the sandbox-sre repository
    - `PROJECT` file: https://github.com/codeready-toolchain/host-operator/blob/master/PROJECT
    - `CSV` file: https://github.com/codeready-toolchain/host-operator/blob/master/config/manifests/bases/host-operator.clusterserviceversion.yaml

4. In case other projects are changed, please provides PR links. - **NA**

2022-09-02 18:33 UTC, alexeykazakov approved these changes

2022-09-07 16:26 UTC, MatousJobanek requested changes
Please drop the new ConditionType - we don't need that

2022-09-07 16:26 UTC, MatousJobanek commented on api/v1alpha1/usersignup_types.go
> +	UserSignupProvisioning ConditionType = "Provisioning"
we don't need a new condition type for this particular reason - it should have been set in the `Complete` one

2022-09-07 16:29 UTC, ranakan19 commented on api/v1alpha1/usersignup_types.go
> +	UserSignupProvisioning ConditionType = "Provisioning"
yeah that makes sense! I'll just keep the reason

2022-09-07 16:29 UTC, alexeykazakov commented on api/v1alpha1/usersignup_types.go
> +	UserSignupProvisioning ConditionType = "Provisioning"
Ah, right! I overlooked that. I was thinking you Kanika are introducing a new reason. Not condition!

2022-09-07 16:32 UTC, ranakan19 commented on api/v1alpha1/usersignup_types.go
> +	UserSignupProvisioning ConditionType = "Provisioning"
done in ec82f43

2022-09-08 08:46 UTC, MatousJobanek approved these changes
Thanks

2022-09-19 15:40 UTC, merged