separate devspacesanalytics from sandbox in registration service analytics
codeready-toolchain/api pull request #360
Opened 2023-05-16 13:24 UTC by ranakan19

## Description
A new struct for DevSpacesAnalytics as a subset of registration service analytics separates the analytics of devspaces from sandbox.

## Checks
1. Did you run `make generate` target? **yes**

2. Did `make generate` change anything in other projects (host-operator, member-operator)? **yes**

3. In case of **new** CRD, did you the following? **N/A**
    - make/generate.mk in this repository
    - `resources/setup/roles/host.yaml` in the sandbox-sre repository
    - `PROJECT` file: https://github.com/codeready-toolchain/host-operator/blob/master/PROJECT
    - `CSV` file: https://github.com/codeready-toolchain/host-operator/blob/master/config/manifests/bases/host-operator.clusterserviceversion.yaml

4. In case other projects are changed, please provides PR links.
    - host-operator: https://github.com/codeready-toolchain/host-operator/pull/806

2023-05-16 13:45 UTC, rajivnathan requested changes

2023-05-16 13:45 UTC, rajivnathan commented on api/v1alpha1/toolchainconfig_types.go
> +	SegmentWriteKey *string `json:"segmentWriteKey,omitempty"`
Not sure if we're currently using it anywhere but I think `WoopraDomain` should probably remain as part of `RegistrationServiceAnalyticsConfig` since previous configuration would have it there.

2023-05-16 22:17 UTC, alexeykazakov commented on api/v1alpha1/toolchainconfig_types.go
> +	SegmentWriteKey *string `json:"segmentWriteKey,omitempty"`
We can't just remove a field which is currently used by our service (reg-service). We will have to do it in a few steps:
- Create new optional (!!!) fields. Do NOT remove the old fields but make them optional instead. They are deprecated now. Merge/deploy the new CRDs.
- Update the configuration CR so it now has both the old and new fields set.
- Update the service to use the new fields only.
- Remove the old fields form the configuration CRs.
- Now you can clean up the CRD/API and remove the old deprecated fields. It's safe to do so because they are not used anymore.

2023-05-16 22:18 UTC, alexeykazakov commented on api/v1alpha1/toolchainconfig_types.go
> +	DevSpacesAnalytics DevSpacesAnalyticsConfig `json:"devSpacesAnalytics,omitempty"`
I would just call it `DevSpaces` because it's already under `RegistrationServiceAnalyticsConfig`.

2023-05-17 03:02 UTC, ranakan19 commented on api/v1alpha1/toolchainconfig_types.go
> +	DevSpacesAnalytics DevSpacesAnalyticsConfig `json:"devSpacesAnalytics,omitempty"`
done in [876a6d5](https://github.com/codeready-toolchain/api/pull/360/commits/876a6d55658cc84083c9c073064c54bb43192562)

2023-05-17 03:45 UTC, ranakan19 commented on api/v1alpha1/toolchainconfig_types.go
> +	SegmentWriteKey *string `json:"segmentWriteKey,omitempty"`
makes sense, Thanks @rajivnathan and @alexeykazakov for clarifying. 
done the first steps in [876a6d5](https://github.com/codeready-toolchain/api/pull/360/commits/876a6d55658cc84083c9c073064c54bb43192562)

2023-05-17 03:57 UTC, alexeykazakov approved these changes
Looks good!

2023-05-17 13:31 UTC, MatousJobanek commented on api/v1alpha1/toolchainconfig_types.go
> +	DevSpaces DevSpaces `json:"devSpacesAnalytics,omitempty"`
the parameter name should match the name specified in the json marker
Don't forget to add also the `// +optional` marker

2023-05-17 13:43 UTC, ranakan19 commented on api/v1alpha1/toolchainconfig_types.go
> +	DevSpaces DevSpaces `json:"devSpacesAnalytics,omitempty"`
done in [a40ca1e](https://github.com/codeready-toolchain/api/pull/360/commits/a40ca1e0fe60c53f901738e5a1704b6f1e73b583)

2023-05-17 15:06 UTC, ranakan19 commented on api/v1alpha1/toolchainconfig_types.go
> +	DevSpaces DevSpaces `json:"devSpacesAnalytics,omitempty"`
and [a329a2d](https://github.com/codeready-toolchain/api/pull/360/commits/a329a2d90f1afa92fc8336743ebdd17f91930872) updates the json marker

2023-05-17 18:54 UTC, rajivnathan approved these changes
Nice! Thanks for addressing the comments 👍

2023-05-19 19:46 UTC, merged