Drop all arbitrary SSO claim properties and annotations
codeready-toolchain/api pull request #393
Opened 2023-12-29 11:23 UTC by sbryzak

## Description
Removed SSO claim properties and annotations from everywhere except the formal IdentityClaims / PropagatedClaims types.

Fixes https://issues.redhat.com/browse/SANDBOX-504

## Checks
1. Did you run `make generate` target? **yes**

2. Did `make generate` change anything in other projects (host-operator, member-operator)? **yes**

3. In case of **new** CRD, did you the following? **yes/no**
    - make/generate.mk in this repository
    - `resources/setup/roles/host.yaml` in the sandbox-sre repository
    - `PROJECT` file: https://github.com/codeready-toolchain/host-operator/blob/master/PROJECT
    - `CSV` file: https://github.com/codeready-toolchain/host-operator/blob/master/config/manifests/bases/host-operator.clusterserviceversion.yaml

4. In case other projects are changed, please provides PR links.
    - host-operator: https://github.com/codeready-toolchain/host-operator/pull/#
    - member-operator: https://github.com/codeready-toolchain/member-operator/pull/#

2024-01-02 12:14 UTC, MatousJobanek requested changes
could you please update the description with the links to the other PRs you created as well - for easy navigation?
Also, since you are removing quite a lot of things, could you please update also:
* registration-service
* toolchain-e2e
* sandbox-sre

repos with the api dependency?

2024-01-02 12:14 UTC, MatousJobanek commented on api/v1alpha1/annotations.go
> +	EmailUserAnnotationKey = AnnotationKeyPrefix + "email"
could we move the annotations to the `useraccount_types.go` file as they are set/used only by UserAccount_controlller?

2024-01-02 12:14 UTC, MatousJobanek commented on api/v1alpha1/annotations.go
> +	EmailUserAnnotationKey = AnnotationKeyPrefix + "email"
The original annotation used `LabelKeyPrefix + "user-email"` key string. Are you sure that you want to change it?
```suggestion
	// EmailUserAnnotationKey is used to set an annotation value in the User resource on the member cluster, that
	// contains the user's Email as set in the user's JWT token.
	EmailUserAnnotationKey = AnnotationKeyPrefix + "user-email"
```

2024-01-02 23:20 UTC, alexeykazakov commented on api/v1alpha1/annotations.go
> +	AccountIDUserAnnotationKey = AnnotationKeyPrefix + "sso-account_id"
I guess you didn't intend to change the actual annotation. It would break our pendo UI.
```suggestion
	AccountIDUserAnnotationKey = AnnotationKeyPrefix + "sso-account-id"
```

2024-01-06 10:02 UTC, sbryzak commented on api/v1alpha1/annotations.go
> +	EmailUserAnnotationKey = AnnotationKeyPrefix + "email"
Good idea, moved.

2024-01-06 10:03 UTC, sbryzak commented on api/v1alpha1/annotations.go
> +	EmailUserAnnotationKey = AnnotationKeyPrefix + "email"
This was intentional, it had actually been planned quite a long time ago as it's more technically correct.

2024-01-06 10:03 UTC, sbryzak commented on api/v1alpha1/annotations.go
> +	AccountIDUserAnnotationKey = AnnotationKeyPrefix + "sso-account_id"
You're right, thanks for spotting this.

2024-01-06 10:06 UTC, sbryzak commented
@MatousJobanek thanks for the review.  I do have branches for both registration service and sandbox-sre, but haven't raised PRs for them yet.  My concern (mainly for registration service) is that we will have multiple branches with the same name which the e2e tests don't support.

2024-02-06 23:32 UTC, alexeykazakov approved these changes

2024-02-07 00:00 UTC, merged